apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: flux-system-sync
  namespace: flux-system
spec:
  interval: 10m0s
  url: https://github.com/42aei/kubecrate.git
  ref:
    tag: v0.4.0
